"""initial schema

Revision ID: 937787e2e61a
Revises: 
Create Date: 2026-07-09 13:37:54.493190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937787e2e61a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employee_emp_id'), 'employee', ['emp_id'], unique=False)
    op.create_table('notifications',
    sa.Column('not_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('server_message', sa.Text(), nullable=False),
    sa.Column('not_type', sa.String(length=70), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('not_id')
    )
    op.create_index(op.f('ix_notifications_not_id'), 'notifications', ['not_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_not_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_employee_emp_id'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
