"""create notification table

Revision ID: 6e825bf9fb01
Revises: dfaa8a09758d
Create Date: 2026-07-08 14:58:41.446153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e825bf9fb01'
down_revision: Union[str, Sequence[str], None] = 'dfaa8a09758d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('not_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('server_message', sa.Text(), nullable=False),
    sa.Column('not_type', sa.String(length=70), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('not_id')
    )
    op.create_index(op.f('ix_notifications_not_id'), 'notifications', ['not_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_not_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
